baseURL = 'https://rayx750.github.io/' # 请确认这里是你的 GitHub Pages 网址
languageCode = 'zh-cn'
title = 'HOME'
theme = 'ananke'
# sectionPagesMenu = "main"

[pagination]
  pagerSize = 10

[params]
  description = "Backend Developer & AI Enthusiast | Focusing on LLM, Search & RecSys"
  custom_css = ["css/custom.css"]

[menu]
  # 首页
  
  # Projects
  # [[menu.main]]
  #   identifier = "projects"
  #   name = "Projects"
  #   url = "/projects/"
  #   weight = 10

  # 直接放 LeetCode
  [[menu.main]]
    identifier = "leetcode"
    name = "Algorithms"  # 菜单上显示的名字
    url = "/leetcode/"
    weight = 20

  # 直接放 Interview
  #[[menu.main]]
  #  identifier = "interview"
  #  name = "Interview"
  #  url = "/interview/"
  #  weight = 30
    
  # 直接放 Tech
  [[menu.main]]
    identifier = "tool"
    name = "Tools"
    url = "/tools/"
    weight = 40